CREATE TABLE `data-evolution-moa.raw_wwi.customers`(
    CustomerID STRING,
    CustomerName STRING,
    BillToCustomerID STRING,
    CustomerCategoryID STRING,
    BuyingGroupID STRING,
    PrimaryContactPersonID STRING,
    AlternateContactPersonID STRING,
    DeliveryMethodID STRING,
    DeliveryCityID STRING,
    PostalCityID STRING,
    CreditLimit STRING,
    AccountOpenedDate STRING,
    StandardDiscountPercentage STRING,
    IsStatementSent STRING,
    IsOnCreditHold STRING,
    PaymentDays STRING,
    PhoneNumber STRING,
    FaxNumber STRING,
    DeliveryRun STRING,
    RunPosition STRING,
    WebsiteURL STRING,
    DeliveryAddressLine1 STRING,
    DeliveryAddressLine2 STRING,
    DeliveryPostalCode STRING,
    DeliveryLocation STRING,
    PostalAddressLine1 STRING,
    PostalAddressLine2 STRING,
    PostalPostalCode STRING,
    LastEditedBy STRING,
    ValidFrom STRING,
    ValidTo STRING
)
PARTITIONED BY (year STRING, month STRING)